"""Add company visibility to rooms

Revision ID: 21cd080aee26
Revises: update_company_domains
Create Date: 2025-08-05 18:42:30.159519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cd080aee26'
down_revision = 'update_company_domains'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('visible_companies', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('visible_companies')
        batch_op.drop_column('visibility_type')

    # ### end Alembic commands ###
