"""Add missing columns to booking table

Revision ID: 522bfca72ffa
Revises: 6cd782c66df9
Create Date: 2025-08-01 16:18:04.684025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522bfca72ffa'
down_revision = '6cd782c66df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_booking_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_booking_company_id', 'company', ['company_id'], ['id'])
        batch_op.create_foreign_key('fk_booking_room_id', 'room', ['room_id'], ['id'])
        batch_op.drop_column('organizer_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('fk_booking_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_booking_company_id', type_='foreignkey')
        batch_op.drop_constraint('fk_booking_room_id', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_id')
        batch_op.drop_column('room_id')
        batch_op.drop_column('company_id')
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
