"""Add organizer info to bookings

Revision ID: 6cd782c66df9
Revises: 0a7b13a99c30
Create Date: 2025-07-19 13:04:41.485721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd782c66df9'
down_revision = '0a7b13a99c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_name', sa.String(length=120), nullable=True))
        batch_op.drop_column('google_calendar_event_id')
        batch_op.drop_column('microsoft_calendar_event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_calendar_event_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_calendar_event_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('organizer_name')

    # ### end Alembic commands ###
