"""Add visibility_type and visible_companies to Booking model

Revision ID: 829b0e659f6e
Revises: 21cd080aee26
Create Date: 2025-08-07 19:12:55.627618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829b0e659f6e'
down_revision = '21cd080aee26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('visible_companies', sa.Text(), nullable=True))
    
    # Set default visibility_type for existing bookings
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE booking SET visibility_type = 'all_companies' WHERE visibility_type IS NULL"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('visible_companies')
        batch_op.drop_column('visibility_type')

    # ### end Alembic commands ###
